[build]
  command = "cd vite-project && npm install && npm run build"
  publish = "vite-project/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200